---
title: "pitch_memo"
output: html_document
---

# 11 million less taxpayers

In May, federal courts permitted immigration agencies to access confidential, personal information of up to 7 million undocumented immigrant taxpayers. This is the first instance where the Internal Revenue Service has shared confidential information for the purposes of immigration investigation. 
Scrutinizing people who use Individual Taxpayer Identification Number, which allows noncitizens and undocumented immigrants to file taxes owed to the IRS 
With new questions of undocumented immigrant’s relationship to taxes, I think it would be timely and relevant to Futuro’s audience to investigate:
How undocumented taxpayer contributions differ in makeup from national 
The portfolio of taxes undocumented immigrants contribute compared to the U.S. total of tax revenue (grouped bar chart with a stacked bar to show how percentages would be if undocumented immigrants filed with legal status)

The Institute on Economic Policy estimates of 11 million undocumented immigrants in the U.S.
Contributing almost 100 billion in taxes
